Coursera/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),


]

courses/urls.py
from django.urls import path

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/<slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', LessonDetailView.as_view(), name='lesson_detail'),
]

memberships/urls.py
from django.urls import path

from memberships.views import MembershipSelectView,PaymentView,UpdateTransactionRecords,CancelSubscription

app_name = 'memberships'

urlpatterns = [
    path('memberships/', MembershipSelectView.as_view(), name='select_membership'),
    path('payments/', PaymentView, name='payment'),
    path('update_transaction/<subscription_id>/update/', UpdateTransactionRecords, name='update_transaction'),
    path('cancel/', CancelSubscription, name='cancel')

]

courses/models.py
from django.db import models
from memberships.models import Membership
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    category = models.CharField(max_length=150)

    def __str__(self):
        return '{}'.format(self.category)

class Course(models.Model):
    creator = models.ForeignKey(User,on_delete = models.CASCADE)
    slug = models.SlugField()
    title = models.CharField(max_length=30)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    description = models.TextField(max_length=400)
    created_time = models.DateTimeField(auto_now=True)
    duration = models.CharField(max_length=10,help_text = 'please use the following formats : 1 Week or 1 Month')
    starting_date = models.DateField(null=True)
    ending_date = models.DateField(null=True)
    allowed_memberships = models.ManyToManyField(Membership,related_name='membershipsallowed')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("courses:course_detail", kwargs={"slug": self.slug})

    def get_courses_related_to_memberships(self):
        return self.courses.all()

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')

class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=30)
    course = models.ForeignKey(Course,on_delete=models.SET_NULL,null=True)
    video_url = models.FileField(upload_to='videos/', null=True)
    thumbnail = models.ImageField()
    position = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("courses:lesson_detail", kwargs={"course_slug": self.course.slug,'lesson_slug':self.slug})

courses/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView,View
from courses.models import Course,Lesson,Category
from memberships.models import UserMembership
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
# Create your views here.

class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.all()
        context['category'] = category
        return context

class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contact.html'

class CourseListView(ListView):
    context_object_name = 'courses'
    template_name = 'courses/course_list.html'
    model = Course


class CourseDetailView(DetailView):
    context_object_name = 'course'
    template_name = 'courses/course_detail.html'
    model = Course

#
class LessonDetailView(View,LoginRequiredMixin):
    def get(self, request, course_slug, lesson_slug, *args, **kwargs):
        course = get_object_or_404(Course, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug)
        user_membership = get_object_or_404(UserMembership, user=request.user)
        user_membership_type = user_membership.membership.membership_type
        course_allowed_membership_type = course.allowed_memberships.all()
        print(course_allowed_membership_type.filter(membership_type=user_membership_type))
        context = { 'lesson': None }
        if course_allowed_membership_type.filter(membership_type=user_membership_type).exists():
            context = {'lesson': lesson}
        return render(request, "courses/lesson_detail.html", context)


# def get(self,request,course_slug,lesson_slug,*args,**kwargs):
#
#     course_qs = Course.objects.filter(slug=course_slug)
#     if course_qs.exists():
#         course = course_qs.first()
#     lesson_qs = course.lessons.filter(slug=lesson_slug)
#     if lesson_qs.exists():
#         lesson = lesson_qs.first()
#     user_membership = UserMembership.objects.filter(user=request.user).first()
#     user_membership_type = user_membership.membership.membership_type
#
#     course_allowed_membership_type = course.allowed_memberships.all()
#     context = {'lessons':None}
#
#     if course_allowed_membership_type.filter(membership_type=user_membership_type).exists():
#         context = {'lesson':lesson}
#
#     return render(request,'courses/lesson_detail.html',context)

courses/templates/courses/course_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}


<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Courses</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Search your course</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form class="course-search-form">
            <input type="text" placeholder="Course">
            <input type="text" class="last-m" placeholder="Category">
            <button class="site-btn btn-dark">Search Couse</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->


<!-- single course section -->
<section class="single-course spad pb-0">
  <div class="container">
    <div class="course-meta-area">
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <div class="course-note">Featured Course</div>
          <h3>{{course.title|capfirst}}</h3>
          <div class="course-metas">
            <div class="course-meta">
              <div class="course-author">
                <div class="ca-pic set-bg" data-setbg="img/authors/2.jpg"></div>
                <h6>Teacher</h6>
                <p>{{course.creator|capfirst}}, <span>Developer</span></p>
              </div>
            </div>
            <div class="course-meta">
              <div class="cm-info">
                <h6>Category</h6>
                <p>{{course.category}}</p>
              </div>
            </div>
            <div class="course-meta">
              <div class="cm-info">
                <h6>Students</h6>
                <p>120 Registered Students</p>
              </div>
            </div>
            <div class="course-meta">
              <div class="cm-info">
                <h6>Reviews</h6>
                <p>2 Reviews <span class="rating">
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star is-fade"></i>
                </span></p>
              </div>
            </div>
          </div>
          <a href="#lessons" class="site-btn price-btn">View Lessons</a>
          <a href="#" class="site-btn buy-btn">Enroll For this Course</a>
        </div>
      </div>
    </div>
    <img src="img/courses/single.jpg" alt="" class="course-preview">
    <div class="row">
      <div class="col-lg-10 offset-lg-1 course-list">
        <div class="cl-item">
          <h4>Course Description</h4>
          <p>{{course.description}}</p>
        </div>
        <div class="cl-item">
          <h4>Certification</h4>
          <p>All our certifications are free , This means that you get a free certification on course completion</p>
        </div>
        <div class="cl-item">
          <h4>The Instructor</h4>
          <p>Mr {{course.creator}}, is a really talented Person and has bagged various certifications, molestie quis ligula in, eleifend rhoncus ipsum. Donec ultrices, sem vel efficitur molestie, massa nisl posuere ipsum, ut vulputate mauris ligula a metus. Aenean vel congue diam, sed bibendum ipsum. Nunc vulputate aliquet tristique. Integer et pellentesque urna. Lorem ipsum dolor sit amet, consectetur. Phasellus sollicitudin et nunc eu efficitur. Sed ligula nulla, molestie quis ligula in, eleifend rhoncus ipsum. Donec ultrices, sem vel efficitur molestie, massa nisl posuere ipsum, ut vulputate mauris ligula a metus. </p>
        </div>
        <div class="cl-item" id="lessons">
          <h4 >Lessons In This Course</h4>
          {% if course.lessons != None  %}
            {% for lesson in course.lessons %}
              <h5 class="pb-3">Lesson {{lesson.position}} <a href="{{ lesson.get_absolute_url }}"><span class="pl-4">{{lesson.title}}</span></a></h5>
            {% endfor %}
          {% endif %}
          {% if object.lessons == '' %}
            <h4>There are no lessons for this course Yet , check back later</h4>
          {% endif %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- single course section end -->


<!-- Page end -->
{% endblock %}

courses/templates/courses/course_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/1.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Courses</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Search your course</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form class="course-search-form">
            <input type="text" placeholder="Course">
            <input type="text" class="last-m" placeholder="Category">
            <button class="site-btn btn-dark">Search Couse</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->

<div class="course-warp">
  <ul class="course-filter controls">
    <li class="control active" data-filter="all">All Courses</li>
  </ul>
<div class="featured-courses">

      <div class="featured-course course-item">
        <div class="row">
          {% for course in courses%}
          <div class="col-lg-6 pb-4">
            <div class="course-info">
              <div class="course-text">
                <h5>Category : {{course.category}}</h5>
                <div class="fet-note">Basic Course</div>
                <a href="{% url 'courses:course_detail' course.slug %}"><h3 class="">{{course.title|capfirst}}</h3></a>
                <p>{{course.description}}</p>
                <div class="students">120 Students</div>
              </div>
              <div class="course-author">
                <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/2.jpg' %}"></div>
                <p>{{course.duration|capfirst}}</p>
                <p>Created By : {{course.creator|capfirst}}, <span>Developer</span> </p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

courses/templates/courses/lesson_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block post_detail_link %}

{% endblock %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Courses/</span>
      <span>Courses/</span>
      <span>Courses/</span>
    </div>
  </div>
</div>
  {% if lesson is not None %}
	<li><a href="{{ lesson.course.get_absolute_url }}">Course : {{ lesson.course.title }}</a></li>
	<li>Title : {{ lesson.title }}</li>
  {% endif %}

<!-- Page info end -->

	<div class='container'>
		<h1>{{ lesson.title }}</h1>
		<div class='row'>
			<div class='col-sm-6 col-md-6'>
				{% if lesson is not None %}
				<h3>Topic : {{ lesson.title }}</h3>

				<video controls
					   controlsList="nodownload"
					   poster="{{ lesson.thumbnail.url }}"
				       src="/static/{{ lesson.video_url }}"
				       width="300"
				       height="200">
				    Sorry, your browser doesn't support embedded videos.
				</video>
				{% else %}
				<h3>Upgrade membership</h3>
				<p>To view this course you'll need to upgrade your membership</p>
				<br>
				<a href="{% url 'memberships:select_membership' %}"><button class="btn btn-warning">Upgrade Membership</button></a>
				<hr>
				{% endif %}
			</div>
		</div>
	</div>

{% endblock content %}