Coursera/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),


]

courses/urls.py
from django.urls import path

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/<slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', LessonDetailView.as_view(), name='lesson_detail'),
]

users/urls.py
from django.urls import path

from users.views import Profile

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),

]

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>About</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<section class="about-us py-5 " id="about-us">
    <div class="container mt-5">
	<div class="row">
		<div class="col-md-6">
		    <h1 class='text-danger'>Welcome!</h1>
		    <h2>Know More About Us</h2>
		    <hr>
		    <p>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore etae magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
		    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		    <button type="button" class="btn btn-danger">Let's Know More</button>

		</div>
		<div class="col-md-6">
		    <img src="http://themebubble.com/demo/marketingpro/wp-content/uploads/2016/10/seo-slide.png "alt="">
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>WebUni - Education Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="WebUni Education Template">
	<meta name="keywords" content="webuni, education, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3">
					<div class="site-logo">
						<img src="{%static 'webuni/img/logo.png' %}" alt="">
					</div>
					<div class="nav-switch">
						<i class="fa fa-bars"></i>
					</div>
				</div>
				<div class="col-lg-9 col-md-9">
					{% if request.user.is_authenticated%}
					<li><a href="{% url 'users:profile' %}" class="site-btn header-btn">Dashboard : {{request.user.username}}</a></li>
					{% else %}
					<li><a href="{% url 'account_login' %}" class="site-btn header-btn">Login</a></li>
					{% endif %}
					<nav class="main-menu">
						<ul>
							<li><a href="{% url 'courses:home' %}">Home</a></li>
							<li><a href="{% url 'courses:about' %}">About us</a></li>
							<li><a href="{% url 'courses:course_list' %}">Courses</a></li>
							<li><a href="blog.html">News</a></li>
							<li><a href="{% url 'courses:contact' %}">Contact</a></li>
							{% if request.user.is_authenticated %}
              <li><a href="{% url 'account_logout' %}">Logout</a></li>
              {% endif %}
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- Header section end -->
{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}


	<!-- banner section -->
	<section class="banner-section spad">
		<div class="container">
			<div class="section-title mb-0 pb-2">
				<h2>Join Our Community Now!</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
			</div>
			<div class="text-center pt-5">
				<a href="{% url 'account_signup' %}" class="site-btn">Register Now</a>
			</div>
		</div>
	</section>
	<!-- banner section end -->


	<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
				<div class="row">
					<div class="widget-item">
						<h4>Contact Info</h4>
						<ul class="contact-list">
							<li>1481 Creekside Lane <br>Avila Beach, CA 931</li>
							<li>+53 345 7953 32453</li>
							<li>yourmail@gmail.com</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Engeneering</h4>
						<ul>
							<li><a href="">Applied Studies</a></li>
							<li><a href="">Computer Engeneering</a></li>
							<li><a href="">Software Engeneering</a></li>
							<li><a href="">Informational Engeneering</a></li>
							<li><a href="">System Engeneering</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Graphic Design</h4>
						<ul>
							<li><a href="">Applied Studies</a></li>
							<li><a href="">Computer Engeneering</a></li>
							<li><a href="">Software Engeneering</a></li>
							<li><a href="">Informational Engeneering</a></li>
							<li><a href="">System Engeneering</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Development</h4>
						<ul>
							<li><a href="">Applied Studies</a></li>
							<li><a href="">Computer Engeneering</a></li>
							<li><a href="">Software Engeneering</a></li>
							<li><a href="">Informational Engeneering</a></li>
							<li><a href="">System Engeneering</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Newsletter</h4>
						<form class="footer-newslatter">
							<input type="email" placeholder="E-mail">
							<button class="site-btn">Subscribe</button>
							<p>*We don’t spam</p>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="footer-warp">
				<ul class="footer-menu">
					<li><a href="#">Terms & Conditions</a></li>
					<li><a href="#">Register</a></li>
					<li><a href="#">Privacy</a></li>
				</ul>
				<div class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
			</div>
		</div>
	</footer>
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script async src="https://relayv2-dev.s3.amazonaws.com/analytics/distrobird_widget.js" data-widget-uid="c97e3cb3-9d88-42cc-a467-9288c7075e84"></script>
	<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
	<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'webuni/js/main.js' %}"></script>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Contact</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Search your course</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form class="course-search-form">
            <input type="text" placeholder="Course">
            <input type="text" class="last-m" placeholder="Category">
            <button class="site-btn btn-dark">Search Couse</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->



<!-- Page -->
<section class="contact-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="contact-form-warp">
          <div class="section-title text-white text-left">
            <h2>Get in Touch</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. </p>
          </div>
          <form class="contact-form">
            <input type="text" placeholder="Your Name">
            <input type="text" placeholder="Your E-mail">
            <input type="text" placeholder="Subject">
            <textarea placeholder="Message"></textarea>
            <button class="site-btn">Sent Message</button>
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="contact-info-area">
          <div class="section-title text-left p-0">
            <h2>Contact Info</h2>
            <p>Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendi sse cursus faucibus finibus.</p>
          </div>
          <div class="phone-number">
            <span>Direct Line</span>
            <h2>+2348091356855</h2>
          </div>
          <ul class="contact-list">
            <li>35 Igando Lane <br>Lagos Nigeria</li>
            <li>+2348091356855</li>
            <li>adebisiayomide07@gmail.com</li>
          </ul>
          <div class="social-links">
            <a href="#"><i class="fa fa-pinterest"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="{% static 'webuni/img/bg.jpg'%}">
  <div class="container">
    <div class="hero-text text-white">
      <h2>Get The Best Free Online Courses</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla <br> dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form class="intro-newslatter">
          <input type="text" placeholder="Course">
          <input type="text" class="last-s" placeholder="Category">
          <button class="site-btn">Search Courses</button>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->


<!-- categories section -->
<section class="categories-section spad">
  <div class="container">
    <div class="section-title">
      <h2>Our Course Categories</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
    </div>
    <div class="row">
      {% for cat in category %}
      <!-- categorie -->
      <div class="col-lg-4 col-md-6">
        <div class="categorie-item">
          <div class="ci-thumb set-bg" data-setbg="{% static 'webuni/img/categories/1.jpg' %}"></div>
          <div class="ci-text">

            <h5>{{cat|capfirst}}</h5>

            <p>Lorem ipsum dolor sit amet, consectetur</p>
            <span>120 Courses</span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- categories section end -->

<!-- signup section -->
<section class="signup-section spad">
  <div class="signup-bg set-bg" data-setbg="{% static 'webuni/img/signup-bg.jpg' %}"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <div class="signup-warp">
          <div class="section-title text-white text-left">
            <h2>Sign up to became a teacher</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
          </div>
          <!-- signup form -->
          <form class="signup-form">
            <input type="text" placeholder="Your Name" name="name">
            <input type="text" placeholder="Your E-mail" name="e-mail">
            <input type="text" placeholder="Your Phone" name="phone">
            <button class="site-btn">Make Request</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- signup section end -->

{% endblock content %}